### PR TITLE
Allow to use insecure rubyzip gem version

### PR DESCRIPTION
**Pull request by RKushnir**
🙈

### CODE REVIEW

**Comment by peeyush-ad2games** [comment]
Can't we downgrade the gem version?

**Comment by RKushnir** [comment]
Would it help?

**Comment by peeyush-ad2games** [comment]
not sure but if the code that causing issue was added in recent release that could?

**Comment by RKushnir** [comment]
It's related to the ZIP format specification, I don't think it's new.
And in description it says "rubyzip version 1.2.1 and earlier"
https://github.com/rubysec/ruby-advisory-db/commit/17985dec28d5fa3b70542048df1b43afe996e0c1

**Review by guigs — APPROVED** [review]
:open_mouth:

**Pull request merged**
